"""Initial

Revision ID: 5e54b592acd4
Revises: 
Create Date: 2024-01-08 19:37:59.532138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5e54b592acd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_station',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('station_name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_weather_station_station_name'), 'weather_station', ['station_name'], unique=False)
    op.create_table('weather_data',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('weather_station_id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('max_temperature', sa.Float(), nullable=True),
                    sa.Column('min_temperature', sa.Float(), nullable=True),
                    sa.Column('precipitation', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['weather_station_id'], ['weather_station.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_weather_data_date'), 'weather_data', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_date'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_weather_station_station_name'), table_name='weather_station')
    op.drop_table('weather_station')
    # ### end Alembic commands ###
