"""add_analysis

Revision ID: fc82edf1227b
Revises: 5e54b592acd4
Create Date: 2024-01-08 21:14:49.095511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc82edf1227b'
down_revision: Union[str, None] = '5e54b592acd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('weather_station_id', sa.Integer(), nullable=False),
    sa.Column('avg_max_temperature', sa.Float(), nullable=True),
    sa.Column('avg_min_temperature', sa.Float(), nullable=True),
    sa.Column('total_precipitation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['weather_station_id'], ['weather_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data_analysis')
    # ### end Alembic commands ###
